---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu/trusty32

suites:
  - name: app
    run_list: [
      "recipe[samplewebapp]"
    ]
  - name: service
    run_list: [
      "recipe[samplewebapp::service]"
    ]